# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


abstract_target 'RnNewArchitectureDemoBase' do
  # Shared pods go here, if any
  
  target 'RnNewArchitectureDemo' do
    # Pods for RnNewArchitectureDemo
  end

  target 'RnNewArchitectureDemo dev' do
    # Pods for RnNewArchitectureDemo dev
  end

  target 'RnNewArchitectureDemo stag' do
    # Pods for RnNewArchitectureDemo sit
  end

  target 'RnNewArchitectureDemo prod' do
    # Pods for RnNewArchitectureDemo prod
  end
  
  config = use_native_modules!
  pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RnNewArchitectureDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
