# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "RnNewArchitectureDemo.xcodeproj")
    build_app(workspace: "RnNewArchitectureDemo.xcworkspace", scheme: "RnNewArchitectureDemo dev")
    upload_to_testflight(
      username: "shiv.tiwari@validusfintech.com",
      app_identifier: "com.validusfintech.cicddemo"
      # app_specific_password: "ValidShiv.123@a"
    )
  end
end
